<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>Area850</RootNamespace>
    <AssemblyName>Area850</AssemblyName>
    <Product>850 Messenger</Product>
    <Company>WARCORE</Company>
    <Authors>WARCORE</Authors>
    <Copyright>Copyright © WARCORE</Copyright>
    <PackageProjectUrl>https://area850.com</PackageProjectUrl>
    <Version>2.1.0</Version>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\850.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\850.ico" />
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
    <PackageReference Include="SIPSorcery" Version="8.0.23" />
    <PackageReference Include="SIPSorceryMedia.Encoders" Version="8.0.7" />
    <PackageReference Include="SIPSorceryMedia.Windows" Version="8.0.14" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Server\**" />
    <None Remove="Server\**" />
    <Page Remove="Server\**" />
    <Compile Remove="wwwroot\**" />
    <None Remove="wwwroot\**" />
    <Compile Remove="Net\**" />
    <Page Remove="Net\**" />
    <Compile Remove="NetHost.cs" />
  </ItemGroup>
</Project>
